context: joris-prd
contexts:
    # secret
    joris-prd:
        endpoints: []
        ca: ENC[AES256_GCM,data:5xz73MvEZmz5cCggTGCFKJY1vYiPSHJGiPfpxOCy7CgC6AcxzKSSiklgNbGuycBQV+iatmw2IqFp/LpALvrm3iZ718P6xdweHYQYQw1ya5nDmok8aJe/CzL9/NkLlAZ0JxoMHzAvAm9hmaoRVR2+FjsucqBYPS2BJUYzbpzNhpbVzJiaVCOYhgajrVMYzJAkCGj6dqIf1YJF2KDtRgJ3qJABEFQ/Nhf7PobwNpjXz8JB5G96lNCf3BtkYvkH/eVL68hdDmkvQWU6aNeUS74bXQQNiA42egcSS2tJ/gMt40r6xQ+/Ki/nTC2RtIVhbHU78FVSqePIC70o27QOHlyUqS4w0/bVSBYLcFnUSKn8dz3bT1RE3haFzX3EgBK9PfXoxrl4jwoLTAP7br51NEBhqZ9uBeXWyAex8Mh4MXAtVPMUjgMAHggRqocz9gQtTgfumLTcJV21hSvDy9NLJDXgoi2H9eKUeBoY6P9NMlMcyb1buHM6xfxVlbgxhGGehnOJnyLIo4LSFnFIC0GShffLl+qMTOAA46kQh0NKLyYN20iBbjav6mtcWa3lHr7QbQ13t2J6rsddfk9PKTyhrfSgXzfFW8A9g2yUTPHzqPkS7XrEqzeGmx1I9/GTHEgfYnQRCM+iR5Kt1NCjHshghWt7w8PoQgZ1Lw96z2CpjFd7dPHty8iRamGTADmfdGTjaHvNyQgr33k0m34YF72zVIVPns67sy5I6IdZcgj1jHTjuNxXmAwttNvx4eSfW42yk6vB5+liTlGvKuMwzx2391gGot4np7HGVclddvvaUotwwfvTnnNtlvpq5ZmOA/Q/8ZJqtpNfrRDt6YRNZYm9wNFkDSq5dJIn7JyOo21jOyBUH9CbQbI+,iv:7nrBb0RdTJenIaL9sTGTBNXfenqibYK4FdpKjd/O8rY=,tag:4hb4EAn0kighJTFsgg6mCw==,type:str]
        crt: ENC[AES256_GCM,data:w5nJMGbF39rsw+j9ThLFbGN7GZfczuH892pXU9Kyj5wv5VI+cZAp/qbxx7GOQVpKttu+5YdHa04m+MfVy8n0RkqrwJ+umT4ZTWg/eb+e/UkxDzak27YlMuT01/SwkUnih/KwjHf5e8WneEP/9WKifuSka8eDBYYOvQ7c69oucWE37wdHZw/wBufmwsdq3EKIE359n967W+hczFSZn3kowdz6s1pznDH2xLrG1gPeYyBN5pb5GWFoFonqHufHL+bHzYSOu9FSIO77+1zsrocPtPS8m5IHs5XuocqXuMfpGzxT0UwFxU4ALkd3Y+ildaIS9FBYAIzbkLSYu/dvKv4PynH1jZTTZynRKwyRMLRRdbbzcVHL4eBt9TrtZ3VTW7HrDmDKbyt1iqMlFNMUvYZmFVPL6aEK2VA69962izLkG/AVfpmypeJMw7gP2Gu6PfGK5uMyk3MUZ07txhCu+YiLQyYhLkEHmMTw3OPW+JHHTNbtFhLN67T33iSG4BIVALiYLHImYgAONdY1z32AM5QLO/RfNwrDMbUXU0EYFGy30ojNVYajVv8yvTmcV7vA3hOjdccMbH4gnBC9LINbFbuHMkEVtmvfo82X0mBn1cVQp9Y5aLq/MheUA8lGsJ5qD53lHgtddS9ehAybPPwcQt8ARo3wPE/pVnrPxynkc1dXhiTyQs5+fxIJVjdgvx3lPWjV75uPFHjH2D5KavApogANsI70MXfx1G6e1a8+knowXPjPc1NeWvn1JSDUaFeRIwFU/4IcMWXHhbOeZNDZq74ItfxUEq4PKHAuq9UxDa3tJ72Kc4Qg0zZIgA==,iv:hybKEhcJd2ByHBLU5kY6+a7iiYxdKrfA4yNbt/I0hDs=,tag:mNMgPwiADgzcLQMdf3fhKw==,type:str]
        key: ENC[AES256_GCM,data:zYjeM1bMYc5zStj68kaFpMLduWMlmvwAy2Q9CDa2hpn0E0fSEcC9IZdLjrNYAHLQTSTFonJIIQlWwJr6OU7knF99Drf+Rnsj3CbnU2jFjMCpV2w7GJicz01lD/S5/53d+yUPddOsGQw+3hGcw3WgqvfNWzUOBfqcvVrzcvC4zsYbSImHDNQZQb5VCKOL937eILClezYvYWMlqWM1dWiKo+oBY7NUMX9Qw/RqAtamDSQ86EMT,iv:RObghf0ROJKVak9tRdJVlonT6KiPgeyMowftGiwcn1o=,tag:J60WXn/mGyDfzHedrwkwyg==,type:str]
sops:
    lastmodified: "2025-07-25T17:54:46Z"
    mac: ENC[AES256_GCM,data:dhX0nPa+/YNZ0GrMKEaFjY/YdtQdh7PiXq9H+JhOwbHPix3jLHYDfr8pYVf7hZzyBI5T//EVVseaGCKMorN4KqrTTe2Gdni990lvdNfg3SWH0w0YK0tqEVxSzit6KD2FEzPmiZU9RU56T4/edE4KmXeBAyxXnnQRak030xU0B4k=,iv:vaYnOWrVrPipgXXRpYlPCMGdQoll3FuaiuTwlwKY/Qs=,tag:72fwLdEZeaQK6K4etkuyzg==,type:str]
    pgp:
        - created_at: "2025-07-25T17:54:46Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DOSLw1rOxnykSAQdAzRhRDq600/JapEqFQAJnNQxSEGU7b2Bcti+6As6xWm0w
            b+4+UduxIqGjZCoQkp9RysfH2IiKIYWv5y5Vc+i3isoGs/XKgZM/0hADB9pRIBmM
            0l4BqqbUefxiTIlIA56ud7KlqEQBtyWpegNwb8xQtWZkoAEBT0xbHEQubBV/ybJq
            INHchyjU8tKEqBbrJXSW5hXp/9YLLug/NwIErD402dzYu8K6m4Jkwsx+Zt7qQALL
            =BZOO
            -----END PGP MESSAGE-----
          fp: C0B224C0F27D4BD397DB7AD23922F0D6B3B19F29!
        - created_at: "2025-07-25T17:54:46Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DQj/fwcZAP5kSAQdAMOvA3oFjQsVrTn4KJaMMBWDzqOuAuIMmXl3H8euj2V8w
            6fJtRUZLzrVjXIqGdk7vTPLYSIhxpowb9UaEfhSKqJ+PP3e6itqQgi0HJv4pURHj
            0l4BI+HmG5QIO+otpugbUdWSySlDh9jNXoM+Pm7RlNOYJ71sCttvSTBzOivELn7g
            6sPL7p/2zfCSnPqd0iDNmMjuGpB7VXnevZvvJrTSn5Z3YYbsZBWeguH8vBMSkkFg
            =PxjY
            -----END PGP MESSAGE-----
          fp: A07340A6AC042B09AAA7F402423FDFC1C6403F99!
    encrypted_comment_regex: ^\s*(enc|encrypt|secret):?.*$
    version: 3.10.2
